# A=5
# B=89
# SUM=A+B
# print(SUM)
# i =0
# while  i<5 :
#     age =int (input("enter the age of the student of five students : "));
#     if(age>18):
#         age=age +5
#     if (age<20):
#         age = age -7
#     i+=1
#     print ("the age you entered is ",age);
'''word = "hello pakistan"
for lettersintheword in word :
    print(lettersintheword)
fruits=("banana","tomato","grape","pomegranade")
for fruit in fruits:
    print(fruit)'''

m =0
while m<5 :
    print ("zaheer is greatest of all time")
if (m==3) :
    m=m+2
else :
    m+=1
print ("i am pakistani")
